wget 'https://www.dropbox.com/s/xm9y42mha4nijpp/ckpt_1.model?dl=1' -O model/ckpt_1.model
wget 'https://www.dropbox.com/s/ppn7uss70g9a9j6/ckpt_2.model?dl=1' -O model/ckpt_2.model
wget 'https://www.dropbox.com/s/qxiy9cbn0cr2pq9/ckpt_2-2.model?dl=1' -O model/ckpt_2-2.model
wget 'https://www.dropbox.com/s/ilwmskybsqrn6n0/ckpt_2-3.model?dl=1' -O model/ckpt_2-3.model
wget 'https://www.dropbox.com/s/eifhg449n5pvjif/ckpt_2-4.model?dl=1' -O model/ckpt_2-4.model
wget 'https://www.dropbox.com/s/0b6r0oifyx9a7rz/ckpt_2-5.model?dl=1' -O model/ckpt_2-5.model
wget 'https://www.dropbox.com/s/6hdscbj7zryh9lt/ckpt_3.model?dl=1' -O model/ckpt_3.model
wget 'https://www.dropbox.com/s/8yrfmmnz9byu2r9/ckpt_4.model?dl=1' -O model/ckpt_4.model
wget 'https://www.dropbox.com/s/7r28jj7h3ph9npq/w2v_all.model?dl=1' -O model/w2v_all.model
python3.6 predict.py $1 $2
